
import React, { useEffect, useState } from 'react';
import { fetchSubscribers, isSupabaseConfigured } from '../services/supabaseClient';

interface SubscribersListModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const SubscribersListModal: React.FC<SubscribersListModalProps> = ({ isOpen, onClose }) => {
  const [subscribers, setSubscribers] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (isOpen) {
      loadSubscribers();
    }
  }, [isOpen]);

  const loadSubscribers = async () => {
    if (!isSupabaseConfigured()) {
       setError("Supabase credentials are not configured. Please add your API key in services/supabaseClient.ts.");
       return;
    }

    setLoading(true);
    setError(null);
    try {
      const data = await fetchSubscribers();
      setSubscribers(data || []);
    } catch (err: any) {
        // Handle common errors
        if (err.message === 'MISSING_CREDENTIALS') {
            setError("Supabase credentials are missing.");
        } 
        else if (
            err.code === 'PGRST205' || 
            (err.message && err.message.includes('relation "public.subscribers" does not exist')) ||
            (err.message && err.message.includes('schema cache'))
        ) {
            setError('Table "subscribers" not found. Please run the setup SQL below.');
        } else {
            setError('Failed to fetch subscribers: ' + (err.message || 'Unknown error'));
        }
    } finally {
      setLoading(false);
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 overflow-y-auto">
      <div className="flex items-center justify-center min-h-screen px-4 pt-4 pb-20 text-center sm:block sm:p-0">
        <div className="fixed inset-0 transition-opacity" aria-hidden="true" onClick={onClose}>
          <div className="absolute inset-0 bg-slate-900 opacity-75"></div>
        </div>

        <span className="hidden sm:inline-block sm:align-middle sm:h-screen" aria-hidden="true">&#8203;</span>

        <div className="inline-block align-bottom bg-white rounded-lg text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-4xl sm:w-full">
          <div className="bg-white px-4 pt-5 pb-4 sm:p-6 sm:pb-4">
            <div className="flex justify-between items-center mb-4">
              <h3 className="text-lg leading-6 font-medium text-slate-900">
                Subscriber Database (Supabase)
              </h3>
              <button onClick={onClose} className="text-slate-400 hover:text-slate-500">
                <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>

            {error && (
               <div className="mb-4 bg-red-50 border-l-4 border-red-500 p-4">
                  <div className="flex">
                    <div className="flex-shrink-0">
                      <svg className="h-5 w-5 text-red-400" viewBox="0 0 20 20" fill="currentColor">
                        <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clipRule="evenodd" />
                      </svg>
                    </div>
                    <div className="ml-3">
                      <p className="text-sm text-red-700">
                        {error}
                      </p>
                      {error.includes('Table "subscribers" not found') && (
                          <div className="mt-2 text-xs font-mono bg-red-100 p-2 rounded overflow-x-auto select-all">
                            create table public.subscribers (<br/>
                            &nbsp;&nbsp;id bigint generated by default as identity primary key,<br/>
                            &nbsp;&nbsp;email text unique not null,<br/>
                            &nbsp;&nbsp;regions text[],<br/>
                            &nbsp;&nbsp;topics text[],<br/>
                            &nbsp;&nbsp;is_subscribed boolean default true,<br/>
                            &nbsp;&nbsp;consent_date timestamp with time zone,<br/>
                            &nbsp;&nbsp;created_at timestamp with time zone default now(),<br/>
                            &nbsp;&nbsp;updated_at timestamp with time zone default now()<br/>
                            );
                          </div>
                      )}
                    </div>
                  </div>
                </div>
            )}

            {loading ? (
              <div className="text-center py-10">
                <svg className="animate-spin h-8 w-8 text-blue-500 mx-auto" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                </svg>
                <p className="mt-2 text-sm text-slate-500">Loading data...</p>
              </div>
            ) : (
              <div className="flex flex-col">
                <div className="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                  <div className="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                    <div className="shadow overflow-hidden border-b border-slate-200 sm:rounded-lg">
                      <table className="min-w-full divide-y divide-slate-200">
                        <thead className="bg-slate-50">
                          <tr>
                            <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-slate-500 uppercase tracking-wider">
                              Email
                            </th>
                            <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-slate-500 uppercase tracking-wider">
                              Status
                            </th>
                            <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-slate-500 uppercase tracking-wider">
                              Regions
                            </th>
                            <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-slate-500 uppercase tracking-wider">
                              Joined
                            </th>
                          </tr>
                        </thead>
                        <tbody className="bg-white divide-y divide-slate-200">
                          {subscribers.map((sub, idx) => (
                            <tr key={sub.id || idx}>
                              <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-slate-900">
                                {sub.email}
                              </td>
                              <td className="px-6 py-4 whitespace-nowrap text-sm text-slate-500">
                                <span className={`px-2 inline-flex text-xs leading-5 font-semibold rounded-full ${sub.is_subscribed ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'}`}>
                                  {sub.is_subscribed ? 'Active' : 'Unsubscribed'}
                                </span>
                              </td>
                              <td className="px-6 py-4 whitespace-nowrap text-sm text-slate-500">
                                {sub.regions?.join(', ')}
                              </td>
                              <td className="px-6 py-4 whitespace-nowrap text-sm text-slate-500">
                                {new Date(sub.created_at).toLocaleDateString()}
                              </td>
                            </tr>
                          ))}
                          {subscribers.length === 0 && !error && (
                            <tr>
                                <td colSpan={4} className="px-6 py-4 text-center text-sm text-slate-500">
                                    No subscribers found.
                                </td>
                            </tr>
                          )}
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
            )}
          </div>
          <div className="bg-slate-50 px-4 py-3 sm:px-6 sm:flex sm:flex-row-reverse">
            <button
              type="button"
              className="mt-3 w-full inline-flex justify-center rounded-md border border-slate-300 shadow-sm px-4 py-2 bg-white text-base font-medium text-slate-700 hover:bg-slate-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 sm:mt-0 sm:ml-3 sm:w-auto sm:text-sm"
              onClick={onClose}
            >
              Close
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
